language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/mvn-home

install:
  # install maven 3.2.5 (default minimum version for building TinkerPop) if it is not in cache already
  - bash .travis.install-maven.sh "3.2.5" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  # visual check that we have the correct maven version installed
  - mvn -version

addons:
  apt:
    packages:
      - oracle-java8-installer
script: 
  - "mvn clean install -Dci"
#notifications:
#  email:
#    recipients:
#      - me@gremlin.guru
#      - robdale@gmail.com
#    on_success: change # default: change
#    on_failure: always # default: always
