language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty

install:
  # include glvs
  - touch gremlin-python/.glv
  - touch gremlin-dotnet/src/.glv
  - touch gremlin-dotnet/test/.glv

addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.4
script: 
  - "mvn clean install -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dci"
